import { getBrief, getStats } from '../api/me'
import type { Brief, Stats } from '../api/types'
import { createSessionCache } from './sessionCache'

/**
 * The re-entry brief is generated by a model, so it comes back *different
 * every time it is asked*. Home used to refetch on every mount, which meant
 * navigating Cards → Home → Notes → Home rewrote the greeting each trip and
 * made the app feel unstable — as if it had forgotten what it just said. A
 * brief is about where this session started, so it's held for the session.
 */
const briefCache = createSessionCache<Brief>({
  key: 'sl:brief:v2',
  ttlMs: 30 * 60 * 1000,
  fetcher: getBrief,
  isValid: (b) => Boolean(b?.headline),
})

/**
 * Stats are real counts rather than model output, so the concern is
 * staleness, not instability — a short TTL keeps Home instant on
 * back-navigation while still reflecting a review session within a minute.
 * Anything that changes them (grading a card, submitting a quiz) clears it
 * outright via `clearStatsCache`.
 */
const statsCache = createSessionCache<Stats>({
  // BUMP THIS WHENEVER `StatsOut` GAINS A FIELD. This cache persists in
  // sessionStorage across reloads, so after the API grew `due_forecast`,
  // `composition` and `daily_goal`, every existing session kept being served
  // the OLD shape — and Home crashed reading `.map` off an absent array.
  // The version in the key is the only thing that invalidates it.
  key: 'sl:stats:v3',
  ttlMs: 60 * 1000,
  fetcher: getStats,
  // Validate the fields the UI actually depends on, not just any one of them.
  // `badges` alone happily accepted a payload from a previous deploy.
  isValid: (s) =>
    Array.isArray(s?.badges) &&
    Array.isArray(s?.due_forecast) &&
    Boolean(s?.composition),
})

export const getCachedBrief = briefCache.get
export const getCachedStats = statsCache.get

/** Call after an action that changes counts, so Home doesn't show stale numbers. */
export const clearStatsCache = statsCache.clear

/** Drop everything cached — call after sign-out so the next user gets their own. */
export function clearBriefCache() {
  briefCache.clear()
  statsCache.clear()
}
