import { getBrief } from '../api/me'
import type { Brief } from '../api/types'

/**
 * The re-entry brief is generated by a model, so it comes back *different
 * every time it is asked*. Home used to refetch on every mount, which meant
 * navigating Cards → Home → Notes → Home rewrote the greeting each trip and
 * made the app feel unstable — as if it had forgotten what it just said.
 *
 * A brief is about where this session started, so it is fetched once and held
 * for the session. `sessionStorage` (not `local`) is the right lifetime: a new
 * tab or a fresh visit is genuinely a new arrival and deserves new copy, while
 * moving around inside one visit does not.
 *
 * The in-flight promise is shared too, so two components mounting together
 * cannot race and produce two different briefs.
 */

const KEY = 'sl:brief:v1'
const TTL_MS = 30 * 60 * 1000

type Cached = { at: number; brief: Brief }

let memory: Cached | null = null
let inflight: Promise<Brief> | null = null

function readStore(): Cached | null {
  try {
    const raw = sessionStorage.getItem(KEY)
    if (!raw) return null
    const parsed = JSON.parse(raw) as Cached
    if (!parsed?.brief?.headline) return null
    if (Date.now() - parsed.at > TTL_MS) return null
    return parsed
  } catch {
    // A malformed or unavailable store is not worth failing the page over.
    return null
  }
}

function writeStore(entry: Cached) {
  try {
    sessionStorage.setItem(KEY, JSON.stringify(entry))
  } catch {
    /* private mode / quota — memory cache still applies */
  }
}

export async function getCachedBrief(): Promise<Brief> {
  if (!memory) memory = readStore()
  if (memory && Date.now() - memory.at <= TTL_MS) return memory.brief
  if (inflight) return inflight

  inflight = getBrief()
    .then((brief) => {
      memory = { at: Date.now(), brief }
      writeStore(memory)
      return brief
    })
    .finally(() => {
      inflight = null
    })

  return inflight
}

/** Drop the cached brief — call after sign-out so the next user gets their own. */
export function clearBriefCache() {
  memory = null
  inflight = null
  try {
    sessionStorage.removeItem(KEY)
  } catch {
    /* ignore */
  }
}
