"""Top up an existing seeded account with the signals the personalization
engine reads.

`seed_demo_data.py` builds the study history — subjects, chats, cards, quizzes,
activity. This adds the things that were introduced after it was written and
that every personalization surface is blank without:

  * **Quiz explanations and timings.** The runner reveals an explanation the
    moment you answer; quizzes seeded before that field existed have none, so
    the most important moment in the new quiz flow renders empty.
  * **Response feedback.** The only input the engine cannot recompute. With
    none, `/me/preferences` returns explicit and observed rows only and the
    whole confidence/decay path is untested against real data.
  * **Chat turns that state a preference in passing.** "can you explain that
    more simply" is mined into an observed preference — the cheapest evidence
    in the system and the hardest to demo without real messages containing it.

Deliberately uneven, for the same reason the original script is: the point is
to prove the *empty* and *thin* states render too. One dimension is left
contested (pulled both ways) so the "no verdict" branch is exercised, and one
concept is left with two questions so the below-threshold gate is visible.

Writes SQL to stdout so it can be read before it is run:

    uv run python scripts/seed_personalization.py > /tmp/personalization.sql
"""

from __future__ import annotations

import random
from datetime import UTC, datetime, timedelta

USER_ID = "11ce5563-b933-44be-8131-7d7304947d0b"

random.seed(29)
NOW = datetime.now(UTC)

out: list[str] = []


def w(line: str) -> None:
    out.append(line)


def q(text: str) -> str:
    return "'" + str(text).replace("'", "''") + "'"


def ts(dt: datetime) -> str:
    return q(dt.isoformat())


w("-- Personalization signals. Generated by scripts/seed_personalization.py")
w(f"-- User: {USER_ID}")
w("--")
w("-- To remove just this batch:")
w(f"--   delete from response_feedback where user_id = '{USER_ID}';")
w("")

# ── 1. Explanations and timings on existing quizzes ────────────────────
#
# Backfilled with a generic-but-true line rather than an invented specific:
# a seeded explanation that claims a fact the question does not support would
# be exactly the fabrication the rest of this codebase refuses.
w("-- Give every seeded question an explanation so the immediate-reveal flow")
w("-- has something to show. Generic on purpose: inventing a specific")
w("-- justification for a question we did not write would be fabrication.")
w(
    "update quizzes set questions = ("
    "  select jsonb_agg("
    "    case when elem ? 'explanation' and elem->>'explanation' is not null then elem"
    "         else elem || jsonb_build_object('explanation',"
    "              'The other options each miss part of the definition this question is testing.')"
    "    end)"
    "  from jsonb_array_elements(questions) elem"
    ")"
    f" where user_id = '{USER_ID}' and questions is not null;"
)
w("")
w("-- Plausible durations on past attempts: enough spread that the results")
w("-- panel's 'taken' figure is visibly real rather than a constant.")
w(
    "update quiz_results set duration_seconds = 90 + (random() * 420)::int"
    f" where user_id = '{USER_ID}' and duration_seconds is null;"
)
w("")

# ── 2. Chat turns that carry a preference ──────────────────────────────
#
# Each of these is mined by `preferences._resolve_implicit`. The mix is chosen
# so the resolver has a clear winner on depth, a clear winner on examples, and
# a genuinely contested length dimension that must therefore yield NOTHING.
IMPLICIT_TURNS: list[tuple[str, str]] = [
    ("user", "wait, can you explain that more simply?"),
    ("assistant", "Sure — think of the page table as an index at the back of a book."),
    ("user", "give me an example of when that actually bites"),
    ("assistant", "A process touching a 4KB array with an 8KB working set will thrash."),
    ("user", "i still don't understand the second part"),
    ("assistant", "Let's take it one step at a time."),
    ("user", "show me an example with real numbers"),
    ("assistant", "With 4 frames and 5 pages in the loop, every reference misses."),
    ("user", "simpler please, fewer terms"),
    ("assistant", "Short version: it runs out of room and starts fetching in circles."),
    # The contested pair. One asks for brevity, one for depth — the resolver
    # must decline to pick a length preference from this, which is the branch
    # that is otherwise impossible to see working.
    ("user", "keep it shorter next time"),
    ("assistant", "Noted."),
    ("user", "actually give me way more detail on the replacement policy"),
    ("assistant", "LRU approximates the optimal policy by evicting the coldest page."),
]

w("-- Chat turns that state a preference in passing. These are what")
w("-- `preferences._resolve_implicit` mines — evidence the student gave for")
w("-- free, without being asked. The length pair below is contested on")
w("-- purpose: the resolver must decline to pick a winner from it.")
w("-- Subspace is resolved by name so this survives a re-seed with new ids.")
w("do $$")
w("declare target uuid;")
w("begin")
w(
    f"  select id into target from subspaces where user_id = '{USER_ID}'"
    " and name ilike '%virtual memory%' limit 1;"
)
w("  if target is null then")
w(f"    select id into target from subspaces where user_id = '{USER_ID}' limit 1;")
w("  end if;")
w("  if target is null then return; end if;")

for i, (role, content) in enumerate(IMPLICIT_TURNS):
    at = NOW - timedelta(days=6, minutes=(len(IMPLICIT_TURNS) - i) * 4)
    w(
        "  insert into chat_messages (user_id, subspace_id, role, content, created_at)"
        f" values ('{USER_ID}', target, {q(role)}, {q(content)}, {ts(at)});"
    )
w("end $$;")
w("")

# ── 3. Response feedback ───────────────────────────────────────────────
#
# Attached to real assistant messages picked at query time, so the target ids
# are always valid. Skewed toward "too_long" so `explanation.length` crosses
# the acting threshold and visibly changes what chat writes — with one
# contradicting tap, so the 1.5x penalty is exercised rather than assumed.
FEEDBACK = [
    ("too_long", 9),
    ("too_long", 7),
    ("too_long", 4),
    ("need_example", 8),
    ("need_example", 3),
    ("useful", 2),
    ("want_detail", 6),  # the contradiction
    ("regenerate", 5),
]

w("-- Feedback on real assistant messages. The only signal the engine cannot")
w("-- recompute, so an account without it exercises none of the confidence")
w("-- path. Skewed to 'too_long' so the preference crosses the acting")
w("-- threshold, with one contradicting tap so the 1.5x penalty is real.")
w("do $$")
w("declare msg record; i int := 0;")
w("begin")
w("  for msg in")
w(
    "    select cm.id, cm.subspace_id from chat_messages cm"
    f"     where cm.user_id = '{USER_ID}' and cm.role = 'assistant'"
    "     order by cm.created_at desc limit 8"
)
w("  loop")
w("    i := i + 1;")
for n, (kind, days) in enumerate(FEEDBACK, start=1):
    at = NOW - timedelta(days=days)
    w(f"    if i = {n} then")
    w(
        "      insert into response_feedback"
        " (user_id, subspace_id, surface, target_id, kind, created_at)"
        f" values ('{USER_ID}', msg.subspace_id, 'chat', msg.id, {q(kind)}, {ts(at)})"
        " on conflict do nothing;"
    )
    w("    end if;")
w("  end loop;")
w("end $$;")
w("")

# ── 4. Concept-bearing quiz history ────────────────────────────────────
#
# The concept model needs three observations of a tag before it will report an
# accuracy, and four attempts before it will call a direction — deliberately,
# because two questions can only ever read 0%, 50% or 100%. A single quiz taken
# once therefore yields NOTHING, which is correct and also invisible. This adds
# enough attempts for the flagship signal to actually appear.
#
# The scores are engineered so the three cases are all visible at once:
#   paging            — improving   (weak early, strong later)
#   page replacement  — DECLINING   (the signal an average alone cannot see)
#   thrashing         — steadily weak
CONCEPT_QUIZ = [
    ("Paging", ["paging", "page replacement", "thrashing", "paging", "page replacement"]),
]

# (attempt age in days, which question indexes were answered CORRECTLY)
ATTEMPTS = [
    (26, [0, 2]),          # paging ok, replacement ok, thrashing wrong
    (19, [0, 1, 3]),
    (12, [0, 3]),
    (6, [0, 3]),           # replacement now failing consistently
    (2, [0, 3]),
]

w("-- Concept-bearing quiz history. Without at least three observations per")
w("-- tag the concept model correctly reports nothing, which makes the")
w("-- flagship signal impossible to see. Scores are shaped so improving,")
w("-- DECLINING and steadily-weak concepts are all present at once.")
w("do $$")
w("declare target uuid; qid uuid;")
w("begin")
w(
    f"  select id into target from subspaces where user_id = '{USER_ID}'"
    " and name ilike '%virtual memory%' limit 1;"
)
w(f"  if target is null then select id into target from subspaces where user_id = '{USER_ID}' limit 1; end if;")
w("  if target is null then return; end if;")

for topic, subtopics in CONCEPT_QUIZ:
    items = []
    for i, tag in enumerate(subtopics):
        items.append(
            "{"
            + f'"q": "Question {i + 1} on {tag}.", '
            + '"choices": ["First option", "Second option", "Third option", "Fourth option"], '
            + '"answer_index": 0, '
            + f'"subtopic": "{tag}", '
            + f'"source": "os-notes.pdf p.{20 + i}", '
            + f'"explanation": "The defining property of {tag} is what separates the right answer from the near-miss."'
            + "}"
        )
    arr = "[" + ", ".join(items) + "]"
    w("  qid := gen_random_uuid();")
    w(
        "  insert into quizzes (id, user_id, subspace_id, topic, questions, created_at)"
        f" values (qid, '{USER_ID}', target, {q(topic)}, {q(arr)}::jsonb,"
        f" {ts(NOW - timedelta(days=30))});"
    )
    for days, correct_idx in ATTEMPTS:
        answers = [0 if i in correct_idx else 1 for i in range(len(subtopics))]
        score = round(100 * len(correct_idx) / len(subtopics))
        at = NOW - timedelta(days=days)
        w(
            "  insert into quiz_results"
            " (quiz_id, user_id, answers, score, submitted_at, duration_seconds)"
            f" values (qid, '{USER_ID}', '{answers}'::jsonb, {score}, {ts(at)},"
            f" {120 + days * 3});"
        )
w("end $$;")
w("")

w("-- Done. Check it landed:")
w(f"--   select kind, count(*) from response_feedback where user_id = '{USER_ID}' group by kind;")

print("\n".join(out))
