"""Generate a realistic study history for one account.

Why this exists: every screen in this app is driven by real stored rows —
the streak, the fortnight chart, the due forecast, the weekly composition,
quiz averages, the Home brief. On an empty account they are all correctly
blank, which makes it impossible to see whether any of them actually work,
and impossible to demo. `IMPLEMENTATION_PLAN.md` flags exactly this under
Phase 2's risk register: "demo quality depends on having realistic quiz
history — build a seed script, not the night before the demo."

Writes SQL to stdout rather than talking to the database itself, so the
output can be read before it is run:

    uv run python scripts/seed_demo_data.py > /tmp/seed.sql
    npx supabase db query -f /tmp/seed.sql --linked

Everything it inserts is tagged in `SEED_TAG` so it can be removed again —
see the DELETE block printed at the top of the output, commented out.

The shape of the data is deliberately uneven: a real student misses days,
scores badly before they score well, and leaves some decks half-reviewed.
A perfectly full heatmap would prove less than a patchy one, because a
patchy one shows the empty states render too.
"""

from __future__ import annotations

import random
import uuid
from datetime import UTC, date, datetime, timedelta

USER_ID = "11ce5563-b933-44be-8131-7d7304947d0b"

# Existing rows on the account, extended rather than duplicated.
RL_SUBJECT = "723d4ff1-41c4-4e7b-acc8-d0b1bde274ce"

SEED_TAG = "seeded-demo"

random.seed(11)  # reproducible: re-running gives the same history


def q(text: str) -> str:
    """Single-quote a SQL string literal."""
    return "'" + text.replace("'", "''") + "'"


def ts(dt: datetime) -> str:
    return q(dt.astimezone(UTC).isoformat())


NOW = datetime.now(UTC).replace(microsecond=0)
TODAY = NOW.date()

out: list[str] = []
w = out.append

w("-- Demo study history. Generated by api/scripts/seed_demo_data.py")
w(f"-- User: {USER_ID}")
w("--")
w("-- To remove everything this inserted, run the block below:")
w("--")
w(f"--   delete from quiz_results where user_id = '{USER_ID}';")
w(f"--   delete from quizzes     where user_id = '{USER_ID}';")
w(f"--   delete from flashcards  where user_id = '{USER_ID}';")
w(f"--   delete from decks       where user_id = '{USER_ID}';")
w(f"--   delete from chat_messages where user_id = '{USER_ID}';")
w(f"--   delete from daily_activity where user_id = '{USER_ID}';")
w("--   (notes/subjects/subspaces are left to you — you authored some.)")
w("")
w("begin;")
w("")

# ── Subjects ──────────────────────────────────────────────────────────
# One is pinned, so the new pin feature has something to demonstrate.
os_subject = str(uuid.uuid4())
la_subject = str(uuid.uuid4())

w("-- Subjects")
w(
    f"insert into subjects (id, user_id, name, tone, pinned, created_at) values "
    f"({q(os_subject)}, {q(USER_ID)}, {q('Operating Systems')}, {q('sky')}, true, "
    f"{ts(NOW - timedelta(days=26))});"
)
w(
    f"insert into subjects (id, user_id, name, tone, pinned, created_at) values "
    f"({q(la_subject)}, {q(USER_ID)}, {q('Linear Algebra')}, {q('mint')}, false, "
    f"{ts(NOW - timedelta(days=19))});"
)
w(f"update subjects set pinned = true where id = {q(RL_SUBJECT)};")
w("")

# ── Subspaces ─────────────────────────────────────────────────────────
# (id, subject, name, days_ago_created, days_ago_touched)
SUBSPACES = [
    (str(uuid.uuid4()), RL_SUBJECT, "Markov Decision Processes", 24, 0),
    (str(uuid.uuid4()), RL_SUBJECT, "Q-Learning", 21, 1),
    (str(uuid.uuid4()), RL_SUBJECT, "Policy Gradients", 12, 4),
    (str(uuid.uuid4()), os_subject, "Virtual Memory", 25, 2),
    (str(uuid.uuid4()), os_subject, "Deadlock", 20, 6),
    (str(uuid.uuid4()), la_subject, "Eigenvalues", 18, 3),
]

w("-- Topics")
for sid, subject, name, made, touched in SUBSPACES:
    w(
        f"insert into subspaces (id, user_id, subject_id, name, created_at, last_activity_at) "
        f"values ({q(sid)}, {q(USER_ID)}, {q(subject)}, {q(name)}, "
        f"{ts(NOW - timedelta(days=made))}, {ts(NOW - timedelta(days=touched))});"
    )
w("")

mdp, qlearn, pg, vmem, deadlock, eigen = [s[0] for s in SUBSPACES]

# ── Chat ──────────────────────────────────────────────────────────────
# Real exchanges, because the Home brief and the note/quiz generators read
# this history back and will quote it. Placeholder lorem would surface as
# nonsense in the brief.
CHATS: list[tuple[str, int, list[tuple[str, str]]]] = [
    (
        mdp,
        6,
        [
            ("user", "What actually makes a process Markov?"),
            (
                "assistant",
                "The Markov property says the next state depends only on the current "
                "state and action — not on how you got there. That's what makes an MDP "
                "tractable: you can write the value of a state as a function of its "
                "immediate reward plus the discounted value of its successors, without "
                "carrying the whole trajectory around.",
            ),
            ("user", "So the history is genuinely thrown away?"),
            (
                "assistant",
                "It is, and that's a modelling choice rather than a fact about the world. "
                "If history matters, you fold it into the state — that's what frame "
                "stacking does in Atari agents. The state grows, but the property holds.",
            ),
        ],
    ),
    (
        mdp,
        3,
        [
            ("user", "Explain the Bellman optimality equation without the notation"),
            (
                "assistant",
                "The best you can do from a state is: take the best available action, "
                "collect its immediate reward, then land somewhere new and do the best "
                "you can from there — discounted, because later reward is worth less. "
                "It's recursive, and that recursion is what value iteration exploits.",
            ),
        ],
    ),
    (
        qlearn,
        5,
        [
            ("user", "Why is Q-learning off-policy?"),
            (
                "assistant",
                "Because the update uses max over next actions, not the action the agent "
                "actually took. It learns the value of the greedy policy while behaving "
                "with something exploratory like epsilon-greedy. SARSA is the on-policy "
                "counterpart — it uses the action actually taken, so it learns the value "
                "of the policy it's running, exploration included.",
            ),
            ("user", "Which one is safer near a cliff?"),
            (
                "assistant",
                "SARSA. Because it accounts for the exploratory steps it will actually "
                "take, it learns to walk further from the edge. Q-learning learns the "
                "optimal path along the cliff and then occasionally falls off it while "
                "exploring. That's the classic Cliff Walking result.",
            ),
        ],
    ),
    (
        vmem,
        2,
        [
            ("user", "What's thrashing really?"),
            (
                "assistant",
                "The working sets of the running processes no longer fit in physical "
                "memory, so every process keeps evicting pages another one is about to "
                "need. CPU utilisation collapses while disk activity spikes — and the "
                "trap is that a scheduler watching only CPU concludes it's idle and "
                "admits more processes, which makes it worse.",
            ),
        ],
    ),
    (
        eigen,
        3,
        [
            ("user", "Intuition for eigenvectors?"),
            (
                "assistant",
                "Directions the transformation doesn't rotate — it only stretches or "
                "squashes them. The eigenvalue is how much. Everything else in the space "
                "gets turned; these are the axes the matrix leaves pointing where they "
                "were.",
            ),
        ],
    ),
]

w("-- Chat history")
for sub, days_ago, turns in CHATS:
    base = NOW - timedelta(days=days_ago, hours=random.randint(0, 6))
    for i, (role, content) in enumerate(turns):
        at = base + timedelta(minutes=2 * i)
        w(
            f"insert into chat_messages (user_id, subspace_id, role, content, created_at) "
            f"values ({q(USER_ID)}, {q(sub)}, {q(role)}, {q(content)}, {ts(at)});"
        )
w("")

# ── Notes ─────────────────────────────────────────────────────────────
NOTES = [
    (
        mdp,
        "Markov decision processes",
        "## The five pieces\n\n"
        "- **States** — everything the agent can observe\n"
        "- **Actions** — what it can do from each state\n"
        "- **Transitions** — P(s' | s, a), the world's response\n"
        "- **Reward** — scalar feedback, the only signal there is\n"
        "- **Discount γ** — how much the future is worth now\n\n"
        "## Why the Markov property matters\n\n"
        "The next state depends only on the current state and action. That is "
        "what lets the value of a state be written recursively, and the whole of "
        "dynamic programming falls out of that.\n\n"
        "> If history matters, put it in the state. Frame stacking is exactly this.\n",
        "agent",
        4,
    ),
    (
        qlearn,
        "Q-learning vs SARSA",
        "| | Q-learning | SARSA |\n"
        "|---|---|---|\n"
        "| Policy | Off-policy | On-policy |\n"
        "| Update uses | max over next actions | action actually taken |\n"
        "| Near a cliff | walks the edge, falls while exploring | keeps a margin |\n\n"
        "The difference is one term in the update. Everything else follows from it.\n",
        "user",
        5,
    ),
    (
        vmem,
        "Thrashing",
        "Working sets stop fitting in RAM, so processes evict each other's pages "
        "in a loop.\n\n"
        "**The trap:** CPU utilisation drops, so a naive scheduler admits *more* "
        "processes, which makes it worse. Detect via page-fault rate, not CPU.\n",
        "user",
        2,
    ),
]

w("-- Notes")
for sub, title, body, origin, days_ago in NOTES:
    at = NOW - timedelta(days=days_ago)
    w(
        f"insert into notes (user_id, subspace_id, title, body_md, origin, created_at, updated_at) "
        f"values ({q(USER_ID)}, {q(sub)}, {q(title)}, {q(body)}, {q(origin)}, {ts(at)}, {ts(at)});"
    )
w("")

# ── Decks and cards ───────────────────────────────────────────────────
# SM-2 state is spread deliberately: some cards overdue, some due today,
# some pushed weeks out. That is what makes the due-forecast chart show a
# shape instead of a single spike.
DECKS = [
    (
        str(uuid.uuid4()),
        mdp,
        "MDP fundamentals",
        [
            ("What does the Markov property state?", "The next state depends only on the current state and action, not on the history."),
            ("What are the five components of an MDP?", "States, actions, transition probabilities, reward function, discount factor."),
            ("What does the discount factor γ control?", "How much future reward is worth relative to immediate reward. γ→0 is myopic, γ→1 is far-sighted."),
            ("What is a policy?", "A mapping from states to actions — deterministic π(s), or stochastic π(a|s)."),
            ("What does the state-value function V^π(s) give?", "Expected return starting from s and following π thereafter."),
            ("Why can an MDP's value function be written recursively?", "Because the Markov property makes a state's value depend only on immediate reward plus its successors' values."),
        ],
    ),
    (
        str(uuid.uuid4()),
        qlearn,
        "Q-learning",
        [
            ("Why is Q-learning off-policy?", "Its update uses max over next actions, not the action actually taken."),
            ("Write the Q-learning update in words.", "Move Q(s,a) toward: reward + γ × best Q available in the next state."),
            ("What does epsilon-greedy trade off?", "Exploration against exploitation — ε chance of a random action, else the greedy one."),
            ("How does SARSA differ from Q-learning?", "It uses the action actually taken next, making it on-policy."),
            ("Which is safer near a cliff, and why?", "SARSA — it accounts for the exploratory steps it will really take, so it keeps a margin."),
        ],
    ),
    (
        str(uuid.uuid4()),
        vmem,
        "Virtual memory",
        [
            ("What is thrashing?", "Working sets exceed physical memory, so processes continuously evict pages each other needs."),
            ("Why does a naive scheduler worsen thrashing?", "It sees low CPU utilisation, concludes the system is idle, and admits more processes."),
            ("What is the working set of a process?", "The set of pages it has referenced in the recent past — its actual live footprint."),
            ("What does TLB stand for and do?", "Translation Lookaside Buffer — caches virtual→physical page translations to avoid walking the page table."),
        ],
    ),
    (
        str(uuid.uuid4()),
        eigen,
        "Eigenvalues",
        [
            ("What is an eigenvector, intuitively?", "A direction the transformation doesn't rotate — only scales."),
            ("What does the eigenvalue tell you?", "How much the eigenvector is stretched (>1), squashed (<1), or flipped (<0)."),
            ("What is the characteristic equation?", "det(A − λI) = 0 — its roots are the eigenvalues."),
        ],
    ),
]

w("-- Decks and cards")
for deck_id, sub, name, cards in DECKS:
    w(
        f"insert into decks (id, user_id, subspace_id, name, created_at) values "
        f"({q(deck_id)}, {q(USER_ID)}, {q(sub)}, {q(name)}, {ts(NOW - timedelta(days=random.randint(8, 20)))});"
    )
    for front, back in cards:
        reps = random.choice([0, 1, 1, 2, 3, 4, 5])
        if reps == 0:
            # Never reviewed — due now, default ease.
            ease, interval, due = 2.5, 0, NOW - timedelta(hours=1)
        else:
            ease = round(random.uniform(1.9, 2.8), 2)
            interval = [1, 3, 7, 14, 30][min(reps - 1, 4)]
            # Some overdue, some due today, most scheduled ahead.
            offset = random.choice([-3, -1, 0, 0, 1, 2, 4, 7, 12, 21])
            due = NOW + timedelta(days=offset)
        w(
            f"insert into flashcards (user_id, deck_id, front, back, ease, interval_days, reps, due_at) "
            f"values ({q(USER_ID)}, {q(deck_id)}, {q(front)}, {q(back)}, {ease}, {interval}, {reps}, {ts(due)});"
        )
w("")

# ── Quizzes and results ───────────────────────────────────────────────
# Scores improve over time, and one topic stays weak. The student model and
# the Home brief both read this, so a flat 100% would make them say nothing
# interesting.
QUIZZES = [
    (
        mdp,
        "Markov decision processes",
        9,
        60,
        [
            ("What does the Markov property guarantee?", ["The next state depends only on the current state and action", "Rewards are always positive", "The policy is deterministic", "The state space is finite"], 0, "Markov Property"),
            ("What does γ = 0 imply?", ["The agent is purely myopic", "The agent ignores rewards", "The agent explores randomly", "The episode never ends"], 0, "Discounting"),
            ("Which is NOT part of an MDP?", ["Learning rate", "States", "Transition probabilities", "Reward function"], 0, "MDP Components"),
            ("A policy maps…", ["States to actions", "Actions to rewards", "Rewards to states", "States to values"], 0, "Policies"),
            ("V^π(s) is…", ["Expected return from s under π", "Immediate reward at s", "Probability of reaching s", "Number of visits to s"], 0, "Value Functions"),
        ],
    ),
    (
        qlearn,
        "Q-learning",
        7,
        40,
        [
            ("Q-learning is off-policy because…", ["Its update uses max over next actions", "It never explores", "It requires a model", "It uses SARSA's update"], 0, "Off-policy Learning"),
            ("Epsilon-greedy balances…", ["Exploration and exploitation", "Bias and variance", "Speed and memory", "On-policy and model-based"], 0, "Exploration"),
            ("SARSA is on-policy because…", ["It uses the action actually taken", "It uses a model", "It is deterministic", "It ignores rewards"], 0, "On-policy Learning"),
            ("Near a cliff, SARSA tends to…", ["Keep a safety margin", "Fall off more often", "Converge slower always", "Ignore the cliff"], 0, "Exploration"),
            ("The Q-learning target is…", ["r + γ·max Q(s',a')", "r only", "γ·Q(s,a)", "max Q(s,a)"], 0, "Bellman Updates"),
        ],
    ),
    (
        vmem,
        "Virtual memory",
        6,
        20,
        [
            ("Thrashing happens when…", ["Working sets exceed physical memory", "The CPU overheats", "Disks are too fast", "Pages are too small"], 0, "Thrashing"),
            ("A TLB caches…", ["Virtual to physical translations", "Disk blocks", "Instructions", "Register values"], 0, "TLB"),
            ("During thrashing, CPU utilisation…", ["Falls", "Rises", "Stays constant", "Doubles"], 0, "Thrashing"),
            ("The working set is…", ["Pages referenced recently", "All allocated pages", "Pages on disk", "The page table"], 0, "Working Set"),
        ],
    ),
    (
        mdp,
        "Bellman equations",
        8,
        90,
        [
            ("The Bellman optimality equation is…", ["Recursive", "Linear in the policy", "Model-free", "Only for finite horizons"], 0, "Bellman Updates"),
            ("Value iteration repeatedly applies…", ["The Bellman optimality operator", "Gradient descent", "Policy gradients", "Monte Carlo rollouts"], 0, "Value Iteration"),
            ("Policy iteration alternates…", ["Evaluation and improvement", "Exploration and exploitation", "Training and testing", "Encoding and decoding"], 0, "Policy Iteration"),
            ("γ close to 1 makes the agent…", ["Far-sighted", "Myopic", "Random", "Greedy"], 0, "Discounting"),
        ],
    ),
]

w("-- Quizzes and results")
# (days_ago, score) — the arc: rough start, steady improvement, one weak spot.
ATTEMPTS = [(9, 60), (7, 40), (6, 20), (4, 80), (2, 100), (1, 75)]
quiz_ids: list[str] = []
for sub, topic, days_ago, _score, items in QUIZZES:
    qid = str(uuid.uuid4())
    quiz_ids.append(qid)
    questions = []
    for stem, choices, answer, subtopic in items:
        opts = ", ".join(q(c) for c in choices)
        questions.append(
            "jsonb_build_object("
            f"'q', {q(stem)}, "
            f"'choices', jsonb_build_array({opts}), "
            f"'answer_index', {answer}, "
            f"'source', {q(topic)}, "
            f"'subtopic', {q(subtopic)})"
        )
    arr = "jsonb_build_array(\n    " + ",\n    ".join(questions) + "\n  )"
    w(
        f"insert into quizzes (id, user_id, subspace_id, topic, questions, created_at) values\n"
        f"  ({q(qid)}, {q(USER_ID)}, {q(sub)}, {q(topic)}, {arr}, "
        f"{ts(NOW - timedelta(days=days_ago))});"
    )

for i, (days_ago, score) in enumerate(ATTEMPTS):
    qid = quiz_ids[i % len(quiz_ids)]
    n = len(QUIZZES[i % len(QUIZZES)][4])  # question count for that quiz
    correct = round(n * score / 100)
    answers = [0] * correct + [1] * (n - correct)
    w(
        f"insert into quiz_results (quiz_id, user_id, answers, score, submitted_at) values "
        f"({q(qid)}, {q(USER_ID)}, '{answers}'::jsonb, {score}, "
        f"{ts(NOW - timedelta(days=days_ago, hours=2))});"
    )
w("")

# ── Daily activity ────────────────────────────────────────────────────
# Drives the streak, the 14-day fortnight chart and the weekly composition.
# Two rest days in the last fortnight, and a live 6-day streak ending today —
# so the streak logic, the "nothing logged" bar state and the glow all have
# something to render.
w("-- Daily activity (streak, fortnight chart, weekly composition)")
REST_DAYS = {8, 11}
for days_ago in range(0, 14):
    day: date = TODAY - timedelta(days=days_ago)
    if days_ago in REST_DAYS:
        continue  # a real student misses days; the chart should show it
    msgs = random.randint(0, 8)
    cards = random.randint(0, 24)
    quizzes_taken = 1 if days_ago in {1, 2, 4, 6, 7, 9} else 0
    seconds = msgs * 60 + cards * 20 + quizzes_taken * 180
    if seconds == 0:
        seconds, cards = 240, 6  # a light day, not an empty one
    w(
        "insert into daily_activity (user_id, day, chat_messages, cards_reviewed, "
        "quizzes_taken, study_seconds) values "
        f"({q(USER_ID)}, {q(day.isoformat())}, {msgs}, {cards}, {quizzes_taken}, {seconds}) "
        "on conflict (user_id, day) do update set "
        "chat_messages = excluded.chat_messages, "
        "cards_reviewed = excluded.cards_reviewed, "
        "quizzes_taken = excluded.quizzes_taken, "
        "study_seconds = excluded.study_seconds;"
    )

w("")
w("commit;")

print("\n".join(out))
